[package]
name = "multitoken_contract"
authors = [""]
compiler_version = ">=1.0.0"
type = "contract"

[dependencies]
aztec = { git = "https://github.com/aztec-labs-eng/aztec-nr", tag = "v6.0.0-rc.1", directory = "aztec" }
compressed_string = { git = "https://github.com/aztec-labs-eng/aztec-nr", tag = "v6.0.0-rc.1", directory = "compressed-string" }
arc403_multitoken_interface = { path = "../arc403_interface/multitoken" }
multitoken_authorization_contract = { path = "src/test/multitoken_authorization_contract" }
generic_proxy = { path = "../generic_proxy" }
