[package]
name = "vault_deployer"
authors = [""]
compiler_version = ">=1.0.0"
type = "contract"

[dependencies]
aztec = { git = "https://github.com/aztec-labs-eng/aztec-nr", tag = "v6.0.0-rc.1", directory = "aztec" }
vault_contract = { path = "../vault_contract" }
token_contract = { path = "../token_contract" }
