name: Update Benchmark Baseline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

concurrency:
  group: update-baseline-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  baseline:
    uses: AztecProtocol/aztec-benchmark/.github/workflows/update-baseline.yml@c55ffd7470d4792ca106c31f2c1d1d5c5697079a # v5.0.0
    with:
      runner: ubuntu-latest
    permissions:
      contents: read
      actions: write
    secrets: inherit
