name: Update Benchmark Baseline

on:
  push:
    branches:
      - dev
      - main
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

concurrency:
  group: update-baseline-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  baseline:
    uses: AztecProtocol/aztec-benchmark/.github/workflows/update-baseline.yml@eea38b7fe8753ea970dea91edc1b45df46fa5987 # main
    with:
      runner: ubuntu-latest
    permissions:
      contents: read
      actions: write
    secrets: inherit
