name: Update Benchmark Baseline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

concurrency:
  group: update-baseline-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  baseline:
    uses: AztecProtocol/aztec-benchmark/.github/workflows/update-baseline.yml@d623993df314206cf1fd08443d10631976bdcf1d
    with:
      runner: ubuntu-latest
      block-duration-ms: "6000"
    permissions:
      contents: read
      actions: write
    secrets: inherit
